[window]
opacity = 0.8
padding = { x = 10, y = 10 }

[font]
size = 12.0

[colors.bright]
black = "#3E3E3E"
blue = "#6CA6F2"
cyan = "#7ECFEF"
green = "#B7EBB7"
magenta = "#E78BE7"
red = "#FF6E6E"
white = "#F1F1F1"
yellow = "#F0DFAF"

[colors.normal]
black = "#2B1B1B"
blue = "#569CD6"
cyan = "#56B6C2"
green = "#8BDB8B"
magenta = "#D55FDE"
red = "#FF5555"
white = "#FFFFFF"
yellow = "#E5C07B"

[colors.primary]
background = "#2B1B1B"
foreground = "#FFD7D7"

[colors.selection]
text = "#2B1B1B"
background = "#FF5555"

[colors.cursor]
text = "#2B1B1B"
cursor = "#FF6E6E"

[cursor]
style = "Block"
unfocused_hollow = true

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "N"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "F11"

[mouse]
hide_when_typing = true

[scrolling]
history = 10000
multiplier = 3

